version: "3"

services:
  postgresql:
    container_name: "fintech-postgresql"
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: product_engine, origination
    ports:
      - "5432:5432"
    networks:
      - fintech-network
    volumes:
      - ./tools/database-dev/configs/create-multiple-db-with-users.sh:/docker-entrypoint-initdb.d/create-multiple-db-with-users.sh:ro
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: "fintech-pgadmin"
    image: dpage/pgadmin4
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    networks:
      - fintech-network
    volumes:
      - ./tools/database-dev/configs/servers.json:/pgadmin4/servers.json:ro
      - ./tools/database-dev/configs/pgpass:/pgadmin4/pgpass:ro
  kafka:
    container_name: "fintech-kafka"
    image: confluentinc/cp-kafka:7.6.0
    hostname: fintech-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://fintech-kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@fintech-kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://fintech-kafka:29092,CONTROLLER://fintech-kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_JMX_PORT: 9997
    ports:
      - "9092:9092"
    networks:
      - fintech-network
  kafka-ui:
    container_name: "fintech-kafka-ui"
    image: provectuslabs/kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'fintech-kafka:29092'
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    ports:
      - "8081:8080"
    networks:
      - fintech-network
  init-kafka:
    container_name: "fintech-init-kafka"
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    networks:
      - fintech-network
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server fintech-kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server fintech-kafka:29092 --create --if-not-exists --topic new-agreements --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server fintech-kafka:29092 --create --if-not-exists --topic scoring-request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server fintech-kafka:29092 --create --if-not-exists --topic scoring-response --replication-factor 1 --partitions 2

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server fintech-kafka:29092 --list
      "
  product_engine:
    container_name: "product_engine"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./product_engine/src/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - fintech-network
    depends_on:
      - postgresql
      - kafka
  origination:
    container_name: "origination"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./origination/src/Dockerfile
    ports:
      - "5002:5002"
    networks:
      - fintech-network
    depends_on:
      - postgresql
      - kafka
  gateway:
    container_name: "gateway"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./gateway/src/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - fintech-network
    depends_on:
      - postgresql
      - kafka
  scoring:
    container_name: "scoring"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./scoring/src/Dockerfile
    ports:
      - "5003:5003"
    networks:
      - fintech-network
    depends_on:
      - postgresql
      - kafka

networks:
  fintech-network:
    name: "fintech-network"
