DATABASE_CONNECT_ORIG="postgresql+asyncpg://postgres:postgres@postgresql/origination"
DATABASE_CONNECT_SCORING="postgresql+asyncpg://postgres:postgres@postgresql/scoring"
DATABASE_CONNECT_PE="postgresql+asyncpg://postgres:postgres@postgresql/product_engine"
KAFKA_INSTANCE="fintech-kafka:29092"
NEW_AGREEMENT_TOPIC="new-agreements"
SCORING_REQUEST="scoring-request"
SCORING_RESPONSE="scoring-response"
